---

# specify the external dns to resolve unknown domain names
remote_server: 8.8.8.8:53

# configuration per services exposed by localdns
servers:
  dns_tcp:
    addr: :8053
    enabled: true
  dns_udp:
    addr: :8053
    enabled: true
  grpc:
    addr: :8080
    enabled: true
  prometheus:
    addr: :9090
    enabled: true

